### ISSUE TITLE
Auto Capture

### ISSUE THREAD

**Issue by mthnzbk** [Lamelynx/GodotGetImagePlugin-Android#7]
Can we enable automatic photo capture with the getCameraImage() method? I need such a feature.

**Comment by Lamelynx** [comment]
I presume  you  whant to take a  photo directly with a call to the plugin? This is not possible due to plugin uses the default camera app. 
To make this work you need to implement a whole camera application into the plugin.
You may look into CameraServer https://docs.godotengine.org/en/stable/classes/class_cameraserver.html . The documentation on this is a bit lackning tough.

**Comment by mthnzbk** [comment]
It does not support Android.

**Comment by Lamelynx** [comment]
You may edit https://github.com/funabab/godot-camera-plugin to get what you want. The plugin has implement a camera into the plugin.

**Comment by mthnzbk** [comment]
modul not working
